GET http://localhost:3000/

###
GET http://localhost:3000/api/persons

###
GET http://localhost:3000/api/persons/655564f6940fa3ceeabbd36e

###
DELETE http://localhost:3000/api/persons/655564f6940fa3ceeabbd36e

###
POST http://localhost:3000/api/persons
Content-Type: application/json

{
  "name": "Erick Parra Guerrero7",
  "number": "0998264721"
}

###
PUT http://localhost:3000/api/persons/65556a1b2ee5e78a89a9199b
Content-Type: application/json

{
  "name": "Fabian Aguilar",
  "number": "0998264721"
}


###
//testing displayed url in fly.io
##
GET https://nodeexpress.fly.dev/

###
GET https://nodeexpress.fly.dev/api/persons

###
GET https://nodeexpress.fly.dev/api/persons/3

###
DELETE https://nodeexpress.fly.dev/api/persons/5

###
POST https://nodeexpress.fly.dev/api/persons
Content-Type: application/json

{
  "name": "Roger Federer",
  "number": "0998265466"
}
